# Generated by Django 3.0.6 on 2020-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='moisterlvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apidata',
            name='motorruntime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
